# Machine Learning 2021/2022
## Assignment 2: Probabilistic Modeling, Unsupervised Learning, Reinforcement Learning
Deadline: 20th of December 2021 9pm

First name: Alessandro  
Last name: De Grandi

## About this assignment

In this assignment you will further deepen your understanding of Probabilistic Modeling, Unsupervised Learning, and Reinforcement Learning (RL).

## Submission instructions

Please write your answers, equations, and code directly in this python notebook and print the final result to pdf (File > Print).
Make sure that code has appropriate line breaks such that all code is visible in the final pdf.
If necessary, select A3 for the PDF size to prevent content from being clipped.

The final pdf must be named name.lastname.pdf and uploaded to the iCorsi website before the deadline expires. Late submissions will result in 0 points.

**Also share this notebook (top right corner 'Share') with teaching.idsia@gmail.com during submission.**

**Keep your answers brief and respect the sentence limits in each question (answers exceeding the limit are not taken into account)**.

Note that there are a total of **140 points in this assignment**.

Learn more about python notebooks and formatting here: https://colab.research.google.com/notebooks/welcome.ipynb

## How to get help

We encourage you to use the tutorials to ask questions or to discuss exercises with other students.
However, do not look at any report written by others or share your report with others.
Violation of that rule will result in 0 points for all students involved. For further questions you can contact the respective TA:

- Probabilistic Modeling: louis@idsia.ch
- Unsupervised Learning: anand@idsia.ch
- Reinforcement Learning: dylan.ashley@idsia.ch

## 1 Probabilistic Modeling (20p)

If $X \sim \text{Rayleigh}(\lambda)$ is a Rayleigh random variable then its probability density function is given by
\begin{equation*}
    p(x; \lambda) = \frac{2x}{\lambda} e^{-\frac{x^2}{\lambda}} \ \ \text{for} \ \ x \geq 0.
\end{equation*}
Let $(X_1, X_2, \ldots, X_N)$ be a random sample from the Rayleigh distribution with parameter $\lambda$ and let $\mathcal{D} = (x_1, x_2, \ldots, x_N)$ be its realization.

### Question 1.1 (4p)

Derive the likelihood function of $\lambda$ given $\mathcal{D}$.  Include all intermediate steps. Simplify sums and products.

$$\mathcal{L}(\lambda; \mathcal{D}) = ?$$

---

**ANSWER HERE**
$$\mathcal{L}(\lambda; \mathcal{D}) =\prod_{i=1}^{N} p(x_{i}; \lambda) = \prod_{i=1}^{N}\frac{2x_{i}}{\lambda} e^{-\frac{x_{i}^2}{\lambda}} = \frac{2^N}{λ^N}e^{\sum_{i=1}^N\frac{-x_i^2}{λ}}\prod_{i=1}^{N}x_i$$

### Question 1.2 (2p)

Derive the log-likelihood. Include all intermediate steps.

$$\ln \mathcal{L}(\lambda; \mathcal{D}) = ?$$

---

**ANSWER HERE**

$\ln \mathcal{L}(\lambda; \mathcal{D}) = ln(\frac{2^N}{λ^N}) + ln(e^{\sum_{i=1}^N\frac{-x_i^2}{λ}}) + ln(\prod_{i=1}^{N}x_i) =$
$= Nln(2)-Nln(\lambda) + {\sum_{i=1}^N\frac{-x_i^2}{λ}}+ \sum_{i=1}^{N}ln(x_i)$

### Question 1.3 (6p)

Derive the maximum likelihood estimate for $\lambda$. Include all intermediate steps.

---

**ANSWER HERE**
$$ \frac{\partial ln \mathcal{L}(\lambda; \mathcal{D})}{\partialλ}=0 $$  
$$\frac{-N}{λ}+ \frac{1}{λ^2}\sum_{i=1}^{N}x_{i}^2 =0 $$
$$  λ = \frac{\sum_{i=1}^{N}x_{i}^2}{N} $$

### Question 1.4 (8p)

Now, suppose we have an inverse gamma prior with parameters $\alpha$ and $\beta$ on $\lambda$, i.e. the probability density function of the prior is
\begin{equation*}
    p(\lambda; \alpha, \beta) = \frac{\beta^\alpha}{\Gamma(\alpha)} \lambda^{-(\alpha + 1)} e^{-\beta / \lambda}
\end{equation*}
where $\Gamma(\cdot)$ is the gamma function defined as $\Gamma(t) = \int_0^\infty u^{t-1} e^{-u} \mathrm{d}u$.

What is the maximum a posteriori estimate for $\lambda$? Include all intermediate steps.

---

**ANSWER HERE**


$p(\lambda|D) = \frac{p(D|λ)p(\lambda)}{p(D)}$

$ \lambda_{MAP}= argmax(p(\lambda|D))$

$ln(p(\lambda|D)=ln(\frac{p(D|λ)p(\lambda)}{p(D)})=ln(p(D|λ))+ln(p(\lambda))-ln(p(D))$

$ \frac{\partial ln(p(\lambda|D))}{\partialλ}=\frac{\partial ln(p(D|lambda))}{\partialλ}+\frac{\partial ln(p(\lambda))}{\partialλ}=0$

$\frac{\partial ln(p(D|lambda))}{\partialλ}=\frac{-N}{λ}+ \frac{1}{λ^2}\sum_{i=1}^{N}x_{i}^2 $

$\frac{\partial ln(p(\lambda))}{\partialλ}=\frac{\partial}{\partialλ}ln(\frac{\beta^\alpha}{\Gamma(\alpha)} \lambda^{-(\alpha + 1)} e^{-\beta / \lambda})= -\frac{\alpha+1}{\lambda}+\frac{\beta}{\lambda^2}$

$\frac{-N}{λ}+ \frac{1}{λ^2}\sum_{i=1}^{N}x_{i}^2 -\frac{\alpha+1}{\lambda}+\frac{\beta}{\lambda^2}=0$

$-N+ \frac{1}{λ}\sum_{i=1}^{N}x_{i}^2 -(\alpha+1)+\frac{\beta}{\lambda}=0$

$\lambda = \frac{(\sum_{i=1}^{N}x_{i}^2) + \beta}{-N+\alpha+1} $









## 2 Unsupervised Learning (30p)

### Question 2.1 (5p)
Given a dataset of points in 1-dimension i.e. $X = \{0, 2, 4, 8, 12 \}$, initialize the k-Means algorithm with 2 cluster center(s) as $\mu_1$ = 0 and $\mu_2$ = 12. Perform 1 iteration (1 E-step and 1 M-step) of the k-Means algorithm with the given cluster initializations.  Compute cluster assignments for all datapoints and cluster centers at the end of the iteration. (Show **all** intermediate computation steps).

---

**ANSWER HERE**

$X = \{x_0, x_1, x_2, x_3, x_4 \}$

$C_1$ center is $\mu_1$

$C_2$ center is $\mu_2$

Compute Euclidian distance between points and cluster centers:

$d(x_0,\mu_1)=0 , d(x_0,\mu_2)=12$

$d(x_1,\mu_1)=2 , d(x_1,\mu_2)=10$

$d(x_2,\mu_1)=4 , d(x_2,\mu_2)=8$

$d(x_3,\mu_1)=8 , d(x_3,\mu_2)=4$

$d(x_4,\mu_1)=12 , d(x_4,\mu_2)=0$

Cluster assignments, assign point to nearest cluster:

$C_1=(x_0,x_1,x_2)$

$C_2=(x_3,x_4)$

Cluster centers:

$\mu_1= \frac{x_0+x_1+x_2}{3}=2$

$\mu_2=\frac{x_3+x_4}{2}=10$









### Question 2.2 (10p)
For the k-Means algorithm, given a dataset $X = \{ x_1, x_2, ... , x_i, ... , x_n \}$ of $n$ points where $x_i \in \mathbb{R}^d$. We want to cluster this into $k$ clusters with centers $\mu = (\mu_1, ..., \mu_k)$. Show that k-Means is guaranteed to converge to a local optimum. Convergence criteria is said to have been met in k-Means when no change of cluster assignment happens for any datapoint between iteration $t$ and $t+1$. *Hint:* Prove that the loss function decreases monotonically in each iteration until convergence (prove it separately for both the E-step and M-step).


---

**ANSWER HERE**

### Question 2.3 (5p)
Find the Eigendecomposition (i.e. eigenvalues and eigenvectors) for \\
\begin{equation}
 A = \begin{bmatrix}
 3 & 5 \\ 4 & 2
 \end{bmatrix}
 \end{equation}


---

**ANSWER HERE**
\begin{equation}
 I = \begin{bmatrix}
 1 & 0 \\ 0 & 1
 \end{bmatrix}
 \end{equation}
 \begin{equation}
 EigenValues: det(A-λI)=0
 \end{equation}
  \begin{equation}
 A-λI =  \begin{bmatrix}  3 & 5 \\ 4 & 2 \end{bmatrix} - \begin{bmatrix}  λ & 0 \\ 0 & λ \end{bmatrix} = \begin{bmatrix}  3-λ & 5 \\ 4 & 2-λ \end{bmatrix}
  \end{equation}
   \begin{equation}
 det(A-λI)= (3-λ)(2-λ)-20 = λ^2 - 5λ -14 = 0
  \end{equation}
   \begin{equation}
 λ = \frac{-b \pm \sqrt{b^2-4ac}}{2a} = \frac{5 \pm \sqrt{81}}{2} = \frac{5 \pm 9}{2}= (7,-2)
  \end{equation}
   \begin{equation}
   EigenVectors: (A-λI)\vec{X}=\vec{0} \;,\;λ_1=7 \;,\;λ_2=-2
   \end{equation}
 \begin{equation}
   λ_1=7 \;,\;\begin{bmatrix}  3-7 & 5 \\ 4 & 2-7 \end{bmatrix}
     \begin{bmatrix}  x_1 \\ x_2 \end{bmatrix}=\begin{bmatrix}  0 \\ 0 \end{bmatrix} => \begin{bmatrix}  -4x_1 + 5x_2 =0 \\ 4x_1-5x_2 =0\end{bmatrix} =>\end{equation}
  \begin{equation}
     x_2=\frac{4}{5}x_1 =>\begin{bmatrix}  5 \\ 4\end{bmatrix}
\end{equation}
 \begin{equation}
   λ_1=-2 \;,\;\begin{bmatrix}  3+2 & 5 \\ 4 & 2+2 \end{bmatrix}
     \begin{bmatrix}  x_1 \\ x_2 \end{bmatrix}=\begin{bmatrix}  0 \\ 0 \end{bmatrix} => \begin{bmatrix}  5x_1 + 5x_2 =0 \\ 4x_1+4x_2 =0\end{bmatrix} =>\end{equation}
\begin{equation}
     x_2=-x_1=>\begin{bmatrix}  -1 \\ 1\end{bmatrix}
\end{equation}




### Question 2.4 (10p)
Prove that a linear projection onto an $M$-dimensional subspace that maximizes the variance of the projected data is defined by the $M$ eigenvectors of the data covariance matrix $S$, corresponding to the $M$ largest eigenvalues. *Hint:* We showed this for the simple 1-D case in the TA session. Now extend this proof for the general case $M < D$ using induction.

---

**ANSWER HERE**

## 3 Reinforcement Learning: Markov Decision Processes (32p)

Suppose a robot is put in a maze with a long corridor. The
corridor is 1 kilometer long and 5 meters wide. The available actions to the robot are moving forward 1 meter, moving backward 1 meter, turning left by 90 degrees and turning right by 90 degrees. If the robot moves and hits the wall, then it will stay in its position and orientation. The robot's goal is to escape from this maze by reaching the end of the long corridor.
**Note: the answers in the following questions should not exceed 5 sentences.**

### Question 3.1 (4p)

Assume the robot receives a +1 reward signal for each time step taken in the
maze and +1000 for reaching the final goal (the end of the long corridor). Then you train the robot for a while, but it seems it still does not perform well at all for navigating to the end of the corridor in the maze. What is happening? Is there something wrong with the reward function?

---

**ANSWER HERE**

The reward function is wrong, it is encouraging the robot to explore the maze taking more steps instead of going for the final goal.

### Question 3.2 (4p)

If there is something wrong with the reward function, how could you fix it? If not, how to resolve the training issues?

---

**ANSWER HERE**

The reward function could be modified to not reward the robot at each time step, rewarding it only for reaching the goal, or even penalize with negative reward the time spent solving the maze, as to encourage it to reach the goal faster.

### Question 3.3 (2p)

The discounted return for a non-episodic task is defined as
$$
G_t = R_{t+1} + \gamma R_{t+2} + \gamma^2 R_{t+3} + \ldots
$$
where $\gamma \in [0, 1]$ is the discount factor.

Rewrite the above equation such that $G_t$ is alone on the left hand side and $G_{t+1}$ is on the right hand side.


---

**ANSWER HERE**

$$
G_t = R_{t+1} + \gamma G_{t+1}
$$


### Question 3.4 (2p)

What is the sufficient condition for this infinite series to be a convergent series?

---

**ANSWER HERE**

Bounded reward sequence and $γ<1 $



### Question 3.5 (5p)

Suppose this infinite series is a convergent series, and each reward in the series is a constant of +1. We know the series is bounded, what is a simple formula for this bound ? Write it down without using summation.

---

**ANSWER HERE**

It is a geometric series:
$\sum_{k=0}^{\infty}{γ}^k$ with  $0\leq\gamma<1$.

So it converges to $\frac{1}{1-γ}$


### Question 3.6 (5p)

Let the task be an episodic setting and the robot is running for $T = 5$ time steps. Suppose $\gamma = 0.9$, and the robot receives rewards along the way $R_1 = −1, R_2 = −0.5, R_3 = 2.5, R_4 = 1, R_5 = 3$. What are the values for $G_0, G_1, G_2, G_3, G_4, G_5$?

---

**ANSWER HERE**


  $G_0= R_1 + \gamma G_1=-1+0.9 \cdot 4.747 = 3.2723$

  $G_1= R_2 + \gamma G_2=-0.5+0.9 \cdot 5.83 = 4.747$

  $G_2= R_3 + \gamma G_3=2.5+0.9\cdot 3.7 = 5.83$

  $G_3= R_4 + \gamma G_4=1+0.9 \cdot 3 = 3.7$

  $G_4= R_5 + \gamma G_5=3+0.9 \cdot 0 = 3$

  $G_5= R_6 + \gamma G_6=0$

### Question 3.7 (5p)

Suppose each reward in the series is increased by a constant $c$, i.e. $R_t \leftarrow R_t + c$.
Then how does it change $G_t$?

---

**ANSWER HERE**
$$
G_t=\sum_{k=0}^\infty\gamma^k(R_{t+1}+c)=\sum_{k=0}^\infty\gamma^k(R_{t+1})+\sum_{k=0}^\infty\gamma^kc=G_t + \sum_{k=0}^\infty\gamma^kc
$$
so $G_t$ is increased by
$
 \sum_{k=0}^\infty\gamma^kc = \frac{c}{1-\gamma}
$

### Question 3.8 (5p)

Now consider episodic tasks, and similar to Question 3.6, we add a constant $c$ to each reward, how does it change $G_t$?

---

**ANSWER HERE**

The additive term in question 3.6 is now :
$\sum_{i=0}^{T-t-1} \gamma ^i c=\sum_{i=0}^{T-t-1} \gamma ^i c =c \cdot \dfrac{ 1 - \gamma ^{T-t}}{1 -\gamma} $


## 4 Reinforcement Learning: Dynamic Programming (58p)

### Question 4.1 (5p)

Write down the Bellman optimality equation for the state value function without using expectation notation, but using probability distributions instead.
Define all variables and probability distributions in bullet points.

---

**ANSWER HERE**
$$V^*(s)=\max_\pi V_\pi(s)=\max_a\sum_{s',r}p(s',r|s,a)[r+\gamma V^*(s')]\quad \forall s$$

where:

*   $V^*(s')$ is the optimal state value function of the following state
*   $s \in S^{+}$ is a state and $s' \in S^{+}$ is the following state
*   $V_\pi(s)$ is the state-value function for policy $\pi$ and state $s$
*   $\pi \in (a|s)$ is the policy
*   $r \in R^{+}$ is the reward
*   $a \in A^{+}$ is an action
*$p(s',r|s,a)$ is the probability of each possible pair of next state, reward given any state, and action
*   $\gamma$ is the discount factor

### Question 4.2 (5p)

Write down the Bellman optimality equation for the state-action value function without using expectation notation, but using probability distributions instead.
Define all variables and probability distributions in bullet points.

---

**ANSWER HERE**

$$Q^*(s,a)=\max_\pi Q_\pi(s,a)=\sum_{s',r}p(s',r|s,a)[r+\gamma \max_{a'}Q^*(s', a')]\quad \forall s$$


where:
*   $a \in A^{+}$ is an action and $a' \in A^{+}$ is the following action
*   $s \in S^{+}$ is a state and $s' \in S^{+}$ is the following state
*   $r \in R^{+}$ is the reward
*   $\pi \in (a|s)$ is the policy
*   $p(s',r|s,a)$ is the probability of each possible pair of next state an reward given any state and action
*   $\gamma$ is the discount factor
*   $Q_\pi(s',a')$ is the action-value function for policy $\pi$
*   $Q^*(s',a')$ is the optimal action-value function for state $s'$ and action $a'$


### Question 4.3 (15p)

Consider a 4x4 gridworld depicted in the following table:

![Grid world](https://i.ibb.co/HdSdKJB/image.png)

The non-terminal states are $S = \{1, 2, \ldots, 14\}$ and the terminal states are $0, 15$.
There are four available actions for each state, that is $A = \{\text{up}, \text{down}, \text{left}, \text{right}\}$.
Assume the state transitions are deterministic and all transitions result in a negative reward of −1.
If the agent hits the boundary, then its state will remain unchanged, e.g. $p(s=8, r=−1|s=8, a=\text{left}) = 1$.
Note: In this exercise, we assume the policy is a deterministic
function and it initially maps each state to an arbitrary action.


Manually run the policy iteration algorithm for one outer iteration. Use the in-place policy iteration algorithm (directly using the updated values for the next value update).
To be specific, run the policy evaluation with a single pass through the states (16 equations, not until convergence) and one time policy improvement.
Assume the initial state value for all 16 cells is 0.0 and the policy initially always outputs the 'left' action.
Write down the equations and detailed numerical computations for the updated values of each cell.
Use a discount factor $\gamma = 0.5$.
Write down the policy after policy improvement.

Read more about this in Sutton & Barto's book http://www.incompleteideas.net/book/ebook/node43.html

---

**ANSWER HERE**

$$
\begin{aligned}
&V_\pi(0) = 1 \cdot [0 + 0.5 \cdot 0] = 0 \qquad & s' = 0  \\
&V_\pi(1) = 1 \cdot [-1 + 0.5 \cdot 0] = -1 \qquad &  s' = 0  \\
&V_\pi(2) = 1 \cdot [-1 + 0.5 \cdot -1] = -1.5 \qquad &  s' = 1  \\
&V_\pi(3) = 1 \cdot [-1 + 0.5 \cdot -1.5] = -1.75 \qquad &  s' = 2  \\
&V_\pi(4) = 1 \cdot [-1 + 0.5 \cdot 0] = -1 \qquad &  s' = 4  \\
&V_\pi(5) = 1 \cdot [-1 + 0.5 \cdot -1] = -1.5 \qquad &  s' = 4  \\
&V_\pi(6) = 1 \cdot [-1 + 0.5 \cdot -1.5] = -1.75 \qquad & s' = 5  \\
&V_\pi(7) = 1 \cdot [-1 + 0.5 \cdot -1.75] = -1.875 \qquad &  s' = 6  \\
&V_\pi(8) = 1 \cdot [-1 + 0.5 \cdot 0] = -1 \qquad &  s' = 8  \\
&V_\pi(9) = 1 \cdot [-1 + 0.5 \cdot -1] = -1.5 \qquad &  s' = 8  \\
&V_\pi(10) = 1 \cdot [-1 + 0.5 \cdot -1.5] = -1.75 \qquad &  s' = 9  \\
&V_\pi(11) = 1 \cdot [-1 + 0.5 \cdot -1.75] = -1.875 \qquad &  s' = 10  \\
&V_\pi(12) = 1 \cdot [-1 + 0.5 \cdot 0] = -1 \qquad &  s' = 12  \\
&V_\pi(13) = 1 \cdot [-1 + 0.5 \cdot -1] = -1.5 \qquad &  s' = 12  \\
&V_\pi(14) = 1 \cdot [-1 + 0.5 \cdot -1.5] = -1.75 \qquad &  s' = 13  \\
&V_\pi(15) = 1 \cdot [0 + 0.5 \cdot 0] = 0 \qquad &  s' = 15
\end{aligned}
$$

### Question 4.4 (12p)

Implement the environment as described in the code skeleton below.
Come up with your own solution and do not copy the code from a third party source.

Then test your implementation of GridWorld using the implementation of policy iteration provided below. Run the code multiple times. Do you always end up with the same policy? Why? (max 4 sentences)

---

**ANSWER HERE**

Yes. The algorithm converges to the global optimum of the value function, that is unique.




#### Imports

In [ ]:
import numpy as np
import itertools

np.set_printoptions(precision=3, linewidth=180)

In [ ]:
side=4
states = np.arange(4*4)
print(states)
states = np.arange(1,4*4-1)

print(states)
print()
for i in range(0,side): print(i,end=" ")
print()
for i in range(side*side-side,side*side): print(i,end=" ")
print()
for i in range(side-1,side*side,side): print(i,end=" ")
print()
for i in range(0,side*side,side): print(i, end=" ")


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

0 1 2 3 
12 13 14 15 
3 7 11 15 
0 4 8 12 


#### Defining the problem

In [ ]:
class GridWorld:

    UP = 0
    DOWN = 1
    LEFT = 2
    RIGHT = 3

    def __init__(self, side=4):
        self.side = side
        # -------------------------
        # Define integer states, actions, and final states as specified
        # in the problem description

        # TODO insert code here
        self.states = np.arange(self.side * self.side)
        self.actions = np.array([self.UP, self.DOWN, self.LEFT, self.RIGHT])
        self.actions_str = ["UP", "DOWN", "LEFT", "RIGHT"]
        self.finals = np.array([0, 15])

        self.upSide=range(0,side)
        self.downSide=range((side*side)-side,side*side)
        self.rightSide=range(side-1,side*side,side)
        self.leftSide= range(0,side*side,side)

        # -------------------------
        self.actions_repr = np.array(['↑', '↓', '←', '→'])

    def _is_terminal(self, s):
        # -------------------------
        # Return True if s is a terminal state and False otherwise

        # TODO insert code here
        isTerminal=False
        if(s in self.finals):
          isTerminal=True
        return isTerminal

        # -------------------------

    def _next_state(self, s, a):
        # -------------------------
        # Returns the next state of the environment if action a were taken
        # while in state s

        #print("STATE")
        #print(s)
        #print("ACTION")
        #print(a)

        # TODO insert code here
        if(a==self.UP):
            if(s in self.upSide): #first row
              return s
            return s-self.side

        elif(a==self.DOWN):
            if(s in self.downSide):
                return s
            return s+self.side

        elif(a==self.LEFT):
            if(s in self.leftSide):
              return s
            return s-1

        elif(a==self.RIGHT):
            if(s in self.rightSide):
              return s
            return s+1



        #return s
        # -------------------------

    def _reward(self, s, s_next, a):
        # -------------------------
        # Return the reward for the given transition as specified
        # in the problem description

        # TODO insert code here
        reward = -1
        if(self._is_terminal(s)):
          reward=0
        return reward

        # -------------------------

    def reset(self):
        # -------------------------
        # Set the internal state of the environment to be sampled uniformly
        # at random from the set of non-terminal states and return the state

        # TODO insert code here
        self.s = np.random.choice(np.arange(1,(self.side**2)-1))
        return self.s

        # -------------------------

    def step(self, a):
        # -------------------------
        # Advances the environment one step using action a and returns s, r, T
        # where s is the next state, r is the reward, and T is a boolean saying
        # whether the episode is done or not

        # TODO insert code here

        #print("STATE")
        #print(self.s)
        #print("ACTION")
        #print(a)

        s_next=self._next_state(self.s,a)
        r=self._reward(self.s,s_next,a)
        T=self._is_terminal(s_next)

        #print("NEXT")
        #print(self.s)
        self.s=s_next
        return self.s,r,T
        # -------------------------

    def print_policy(self, policy):
        P = np.array(policy).reshape(self.side, self.side)
        print(self.actions_repr[P])

    def print_values(self, values):
        V = np.array(values).reshape(self.side, self.side)
        print(V)

#### Policy iteration

In [ ]:
def transition_prob(s, s_next, a):
    return 1 if problem._next_state(s, a) == s_next else 0


def eval_policy(problem, policy, value, gamma=0.9, theta=0.01):
    p = transition_prob
    r = problem._reward

    while True:
        delta = 0
        for s in problem.states:
            v = value[s]
            value[s] = np.sum(
                [
                    p(s, next_s, policy[s])
                    * (r(s, next_s, policy[s]) + gamma * value[next_s])
                    for next_s in problem.states
                ]
            )
            delta = max(delta, abs(v - value[s]))

        if delta < theta:
            return value


def improve_policy(problem, policy, value, gamma=0.9):
    p = transition_prob
    r = problem._reward

    stable = True
    for s in problem.states:
        actions = problem.actions

        b = policy[s]
        policy[s] = actions[
            np.argmax(
                [
                    np.sum(
                        [
                            p(s, next_s, a) * (r(s, next_s, a) + gamma * value[next_s])
                            for next_s in problem.states
                        ]
                    )
                    for a in actions
                ]
            )
        ]
        if b != policy[s]:
            stable = False

    return stable


def policy_iteration(problem, gamma=0.9, theta=0.01):
    # Initialize a random policy
    policy = np.array([np.random.choice(problem.actions) for s in problem.states])
    print("Initial policy")
    problem.print_policy(policy)
    # Initialize values to zero
    values = np.zeros_like(problem.states, dtype=np.float32)

    # Run policy iteration
    stable = False
    for i in itertools.count():
        print(f"Iteration {i}")
        values = eval_policy(problem, policy, values, gamma, theta)
        problem.print_values(values)
        stable = improve_policy(problem, policy, values, gamma)
        problem.print_policy(policy)
        if stable:
            break

    return policy, values

In [ ]:
# Run the below code, please include the output in your submission
problem = GridWorld()
policy_iteration(problem, gamma=0.5)

Initial policy
[['↑' '→' '↓' '←']
 ['→' '←' '←' '←']
 ['↑' '↑' '←' '↓']
 ['↑' '↑' '↑' '←']]
Iteration 0
[[ 0.    -1.999 -2.    -2.   ]
 [-1.999 -2.    -2.    -2.   ]
 [-2.    -2.    -2.    -1.5  ]
 [-2.    -2.    -2.    -1.   ]]
[['↑' '←' '←' '←']
 ['↑' '↑' '↑' '↓']
 ['↑' '↑' '→' '↓']
 ['↑' '↑' '→' '↓']]
Iteration 1
[[ 0.    -1.    -1.5   -1.75 ]
 [-1.    -1.5   -1.75  -1.508]
 [-1.5   -1.75  -1.508 -1.008]
 [-1.75  -1.875 -1.008 -0.008]]
[['↑' '←' '←' '←']
 ['↑' '↑' '↑' '↓']
 ['↑' '↑' '↓' '↓']
 ['↑' '→' '→' '↓']]
Iteration 2
[[ 0.    -1.    -1.5   -1.75 ]
 [-1.    -1.5   -1.75  -1.502]
 [-1.5   -1.75  -1.502 -1.002]
 [-1.75  -1.502 -1.002 -0.002]]
[['↑' '←' '←' '←']
 ['↑' '↑' '↑' '↓']
 ['↑' '↑' '↓' '↓']
 ['↑' '→' '→' '↓']]


(array([0, 2, 2, 2, 0, 0, 0, 1, 0, 0, 1, 1, 0, 3, 3, 1]),
 array([ 0.   , -1.   , -1.5  , -1.75 , -1.   , -1.5  , -1.75 , -1.502, -1.5  , -1.75 , -1.502, -1.002, -1.75 , -1.502, -1.002, -0.002], dtype=float32))

### Question 4.5 (5p)

Let's run policy iteration with $\gamma = 1$. Describe what is happening. Why is this the case? Give an example. What is $\gamma$ trading off and how does it affect policy iteration? (max 8 sentences)

---

**ANSWER HERE**

The convergence of the series is not guaranteed when $\gamma = 1$. So if the series diverges, the program never terminates.

When $\gamma$ is closer to 1 the series takes longer to converge and the agent is more farsighted, takes more into account future rewards.

When $\gamma$ is closer to 0 the series converges sooner and the agent is more myopic.



In [ ]:
policy_iteration(problem, gamma=1.0)

Initial policy
[['←' '↑' '↑' '↑']
 ['↑' '←' '↓' '→']
 ['↓' '→' '↑' '←']
 ['↓' '←' '←' '↑']]
Iteration 0


KeyboardInterrupt: ignored

### Question 4.6 (16p)

Implement Q-learning using the code skeleton below.
Come up with your own solution and do not copy the code from a third party source.
Then execute the block to show that your solution reached when $\gamma = 0.5$ is optimal.

In [ ]:
#tests
print(np.random.random())
print(np.random.randint(4))
val = np.array([0.1,0.3,0.2,0.4])
print(val)
print(np.random.randint(4))
print(np.argmax(val))
print(np.zeros((len(problem.states), len(problem.actions)), dtype=float))

0.7466592998496482
0
[0.1 0.3 0.2 0.4]
0
3
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
problem = GridWorld()
GAMMA = 0.5
sa_values = np.zeros((len(problem.states), len(problem.actions)), dtype=float)

def epsilon_greedy(a_values, epsilon):
    # -------------------------
    # This function takes a list a_values where each index i corresponds
    # to an estimate of the value of action i and then performs
    # epsilon-greedy action selection to sample and return an action

    # TODO insert code here
    if np.random.random() < epsilon:
        return np.random.randint(len(a_values))
    else:
        return np.argmax(a_values)

    # -------------------------

iters = 100000
#iters = 1000
epsilon=0.5
learning_rate=0.1

for i in range(iters):
    s = problem.reset()
    #print("initial state",s)
    done = False
    while not done:
        # -------------------------
        # Perform one step of Q-learning here using sa_values to store
        # the action-value estimates and epsilon_greedy to perform the
        # action selection
        #
        # Play around to find a good step size

        # TODO insert code here


        action = epsilon_greedy(sa_values[s], epsilon)
        s_next, reward, done = problem.step(action)
        sa_values[s, action] = sa_values[s, action] + learning_rate * \
          (reward + GAMMA* np.max(sa_values[s_next]) - sa_values[s, action])
        s = s_next

        #debug
        #if(i%(iters/5)==0):
          #print(i)
          #print("action",action)
          #print(s,problem.actions_str[action],s_next, reward, done)
          #print(sa_values)




        # -------------------------

optimal_policy_state_values = policy_iteration(problem, gamma=0.5)[1]
learned_policy_state_values = np.max(sa_values, axis=1)

print('Optimal Policy State Values:')
print(optimal_policy_state_values)
print('Learned Policy State Values:')
print(learned_policy_state_values)
print('Root Mean Squared Value Error: {0:.8f}'.format(
    np.sqrt(np.mean(np.square(optimal_policy_state_values - learned_policy_state_values)))))

Initial policy
[['↑' '↓' '↑' '↑']
 ['→' '↑' '←' '↑']
 ['→' '↓' '↓' '→']
 ['↑' '↓' '←' '→']]
Iteration 0
[[ 0.    -2.    -1.992 -1.992]
 [-2.    -2.    -2.    -1.996]
 [-1.992 -1.992 -1.996 -1.992]
 [-1.996 -1.992 -1.996  0.   ]]
[['↑' '←' '↑' '↑']
 ['↑' '↓' '↑' '↑']
 ['←' '↓' '←' '↓']
 ['↑' '↑' '→' '↓']]
Iteration 1
[[ 0.    -1.    -1.998 -1.998]
 [-1.    -1.998 -1.999 -1.999]
 [-1.998 -1.999 -2.    -1.   ]
 [-1.999 -2.    -1.     0.   ]]
[['↑' '←' '←' '↑']
 ['↑' '↑' '↑' '↓']
 ['↑' '↑' '↓' '↓']
 ['↑' '→' '→' '↓']]
Iteration 2
[[ 0.   -1.   -1.5  -2.  ]
 [-1.   -1.5  -1.75 -1.5 ]
 [-1.5  -1.75 -1.5  -1.  ]
 [-1.75 -1.5  -1.    0.  ]]
[['↑' '←' '←' '↓']
 ['↑' '↑' '↑' '↓']
 ['↑' '↑' '↓' '↓']
 ['↑' '→' '→' '↓']]
Iteration 3
[[ 0.   -1.   -1.5  -1.75]
 [-1.   -1.5  -1.75 -1.5 ]
 [-1.5  -1.75 -1.5  -1.  ]
 [-1.75 -1.5  -1.    0.  ]]
[['↑' '←' '←' '↓']
 ['↑' '↑' '↑' '↓']
 ['↑' '↑' '↓' '↓']
 ['↑' '→' '→' '↓']]
Optimal Policy State Values:
[ 0.   -1.   -1.5  -1.75 -1.   -1.5  -1.75 -1.5  -1.5  